










version: '3.8'

services:
  # IPFS node for storage
  ipfs:
    image: ipfs/go-ipfs:v0.19.0
    ports:
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ./data/ipfs:/data/ipfs

  # Anvil EVM testnet for smart contracts
  anvil:
    image: ghcr.io/foundry-rs/foundry:v0.2.1
    command: anvil --fork-url https://base-sepolia.infura.io/v3/YOUR_INFURA_PROJECT_ID
    ports:
      - "8545:8545"

  # Coordinator service
  coordinator:
    build:
      context: ./coordinator
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - PORT=3001
      - BASE_SEPOLIA_RPC_URL=http://anvil:8545
    ports:
      - "3001:3001"
    depends_on:
      - anvil

  # Provider daemon instances
  provider1:
    build:
      context: ./daemon
      dockerfile: Dockerfile.dev
    environment:
      - DAEMON_ID=provider1
      - COORDINATOR_URL=http://coordinator:3001
    depends_on:
      - coordinator

  # Provider daemon instances
  provider2:
    build:
      context: ./daemon
      dockerfile: Dockerfile.dev
    environment:
      - DAEMON_ID=provider2
      - COORDINATOR_URL=http://coordinator:3001
    depends_on:
      - coordinator

  # Verifier service
  verifier:
    build:
      context: ./verifier
      dockerfile: Dockerfile.dev
    environment:
      - VERIFIER_COORDINATOR_URL=http://coordinator:3001
    depends_on:
      - coordinator








