

version: '3.8'

services:
  relay:
    image: golang:1.20-alpine
    working_dir: /app
    volumes:
      - ../services/relay:/app
    command: sh -c "go mod tidy && go run main.go"
    ports:
      - "8080:8080"

  indexer:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ../services/indexer:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3001:3001"

  ai-router:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - ../services/ai-router:/app
    command: sh -c "pip install fastapi uvicorn && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"

  web:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ../apps/web:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"

  meilisearch:
    image: getmeili/meilisearch:v0.24.0
    ports:
      - "7700:7700"

  nats:
    image: nats:latest
    command: ["nats", "-js"]
    ports:
      - "4222:4222"
