












# CLI Development Container

FROM python:3.10-slim AS builder

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt && \
    poetry install

CMD ["poetry", "run", "og"]










