
















version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: aegisgov_db
    environment:
      POSTGRES_DB: aegisgov
      POSTGRES_USER: aegisgov
      POSTGRES_PASSWORD: aegisgov
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aegisgov"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: aegisgov_api
    environment:
      DATABASE_URL: postgres://aegisgov:aegisgov@db:5432/aegisgov
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:














