










name: Deploy Contracts to Base Sepolia

on:
  push:
    branches: [ main ]
    paths:
      - 'contracts/**'
      - '.github/workflows/deploy-contracts.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Install dependencies
      working-directory: ./contracts
      run: forge install

    - name: Build contracts
      working-directory: ./contracts
      run: forge build

    - name: Deploy to Base Sepolia
      env:
        BASE_SEPOLIA_RPC_URL: ${{ secrets.BASE_SEPOLIA_RPC_URL }}
        PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
      working-directory: ./contracts
      run: |
        echo "Deploying contracts..."
        # In a real implementation, we would use forge script here

    - name: Verify deployment
      if: success()
      run: echo "Contracts deployed successfully!"





